### ISSUE TITLE
Add `status`, `message`, and `data` properties to `Error` schema

### ISSUE THREAD

**Issue by rafasc** [outline/openapi#5]
I am using a generated client based on the openapi spec to interact with our outline server. 
I am trying to pass down the error messages when the API reports failures, but the generated client does not expose all the values returned because the `Error` schema is defined as:
https://github.com/outline/openapi/blob/3692d4578867767a676de848a3eeccee4d87ee23/spec3.yml#L3459-L3466

while the API returns a more complete object for `Errors`. E.g.:
```
{
  "ok": false,
  "error": "authorization_error",
  "status": 403,
  "message": "Authorization error"
}
```
The type of these values may change, c.f.:
https://github.com/outline/outline/blob/5c999f5327ccb7e53bdfa3fa903250728e9a761f/server/onerror.ts#L102-L106

What would be the preferable solution here? Describe the behaviour on the spec or attempt to normalized the returned values?

**Comment by tommoor** [comment]
> The type of these values may change

I'm not 100% sure what you mean here, which are you referring to? It makes sense to expose these in the schema though

**Comment by rafasc** [comment]
My question is whether it makes sense to cast these values to specific types, for example casting `message` to string before we update the schema.

**Comment by tommoor** [comment]
I see, it wouldn't hurt – especially as errors can come from lots of different places as much as we might try and standardize
